var app=angular.module("dataApp",['ui.router','ng.post','data.controller','data.service','data.directive']);
app.config(['$stateProvider','$urlRouterProvider',function($stateProvider,$urlRouterProvider){
	   $stateProvider.state('mainpage',{
	   	     url:'/mainpage',
	   	     templateUrl:'template/mainpage.html',
	   	     controller:'mainpageCtrl'
	   }).state('mainpage.login',{
	   	     url:'/login',
	   	     templateUrl:'template/login.html',
	   	     controller:'loginCtrl'
	   }).state('mainpage.login2',{
	   	     url:'/login2',
	   	     templateUrl:'template/login2.html',
	   	     controller:'login2Ctrl'
	   }).state('mainpage.register',{
	   	     url:'/register',
	   	     templateUrl:'template/register.html',
	   	     controller:'registerCtrl'
	   }).state('mainpage.data',{
	   	     url:'/data',
	   	     templateUrl:'template/data.html',
	   	     controller:'dataCtrl'
	   }).state('mainpage.datacj',{
	   	     url:'/datacj',
	   	     templateUrl:'template/datacj.html',
	   	     controller:'datacjCtrl'
	   }).state('mainpage.detail',{
	   	     url:'/detail',
	   	     templateUrl:'template/detail.html',
	   	     controller:'detailCtrl'
	   })
	   //编辑页面
	   .state('mainpage.editor',{
	   	     url:'/editor/:id',
	   	     templateUrl:'template/editor.html',
	   	     controller:'editorCtrl'
	   })
	   //添加页面
	   .state('mainpage.adddata',{
	   	     url:'/adddata',
	   	     templateUrl:'template/adddata.html',
	   	     controller:'adddataCtrl'
	   })
	   //超级管理员详情页面
	   .state('mainpage.superxq',{
	   	     url:'/superxq/:id',
	   	     templateUrl:'template/superxq.html',
	   	     controller:'superxqCtrl'
	   })
	   $urlRouterProvider.when('','/mainpage/login');
}])
